### ISSUE TITLE
Unable to Copy Quivers Correctly

### ISSUE THREAD

**Issue by livejamie** [fikal/PoeTradeItemCopy#10]
Seems like it's omitting part of the names:

Output:
> Rarity: Magic
The Shaper's  of the Fox
Broadhead Arrow Quiver
Item Level: 81
Quality: 0
Implicits: 1
Adds 6 to 12 Physical Damage to Bow Attacks
+18 to Dexterity
Adds an additional Arrow
Shaped

Should be "The Shaper's Broadhead Arrow Quiver of the Fox"

Output:
> Rarity: Magic
The Shaper's  of the Elder
Spike-Point Arrow Quiver
Item Level: 80
Quality: 0
Implicits: 1
23% increased Global Critical Strike Chance
Adds an additional Arrow
5% chance to Blind Enemies on Hit with Attacks
Shaped

Should be "The Shaper's Spike-Point Arrow Quiver of the Elder"

From this search: http://poe.trade/search/otakiteninomiu

**Comment by fikal** [comment]
Thanks . Fixed in latest
