### ISSUE TITLE
can't copy items into PoB anymore 

### ISSUE THREAD

**Issue by sskilmister** [fikal/PoeTradeItemCopy#14]
i had this issue yesterday but i just installed the new script and that seemed to work. im now having this problem again... everything looks fine except when i click copy, it wont do anything in path of building. any help would be great! thanks

love this thing by the way, ive never had a problem with it for the year ive used it

**Comment by fikal** [comment]
What browser are you using?  Everything seems to be working perfect with Chrome Version 65.0.3325.181.

**Comment by wlfbck** [comment]
nevermind, misunderstood sskilmister. Will open another issue for the bug i'm facing right now.

**Comment by sskilmister** [comment]
I'm running Firefox as well. Mine is working again however. I'll post my version when or if I have this problem again.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
