### ISSUE TITLE
returnImplicitCount wrongly counts all crafted as implicits

### ISSUE THREAD

**Issue by wlfbck** [fikal/PoeTradeItemCopy#15]
The problem lies in this line:
`this.htmlDiv.find("ul .mods:not(.withline) li").each(function(){`
This goes over all mods, which in turn together with 
`if (that.text().indexOf('crafted') !== -1) {`
counts all crafts as implicits.

Basically you would only need to check the very first mod for being enchanted or crafted. (Do crafted implicits even exist? Can't think of any of the top of my head).

**Comment by fikal** [comment]
This will not be needed in the next version of the script
