### ISSUE TITLE
URL Matching (Script Not Working)

### ISSUE THREAD

**Issue by StarScream159** [fikal/PoeTradeItemCopy#18]
poe.trade has forced https and the script looks for the domain http://poe.trade to execute. It therefore will not trigger. The script needs to be edited, line 7 and change to be https://poe.trade. It works after that.

Sure also change the currency line below it too.

**Comment by profucius** [comment]
I have also found this fixes the issue. Please update the main script. Thank you.

**Comment by fikal** [comment]
Fixed and will be in next build
