### ISSUE TITLE
Make copied item information "identical" to the data copied ingame

### ISSUE THREAD

**Issue by Eruyome** [fikal/PoeTradeItemCopy#5]
Hey,

just a suggestion, could be asking too much. I'm not sure how many tools out there parse the ingame item information, I know of PoB, http://www.pathof.info/ and of course my PoE-TradeMacro, there could be more. Currently the data copied with your script from poe.trade only works with PoB. If you could rework it to make it more like the data that you get via ctrl + c ingame it would be compatible with more tools. For example, TradeMacro has a hidden dev function where you can parse and search items by using this data, this way it's not neccessary to be in possession of that item.

Like this:

```
Rarity: Unique
Ephemeral Edge
Dusk Blade
--------
One Handed Sword
Physical Damage: 48-135 (augmented)
Critical Strike Chance: 5.00%
Attacks per Second: 1.30
Weapon Range: 9
--------
Requirements:
Level: 70
Str: 60
Dex: 111
--------
Sockets: G-R-R 
--------
Item Level: 68
--------
40% increased Accuracy Rating
--------
150% increased Physical Damage
+10 to Intelligence
50% increased Global Critical Strike Chance
10% reduced maximum Life
50% increased maximum Energy Shield
0.91% of Physical Attack Damage Leeched as Mana
--------
In the rift between future and past,
life passes quickly.

```

**Comment by fikal** [comment]
This will be done in the next version
