### ISSUE TITLE
the script is on but tampermonkey says there's no scripts running

### ISSUE THREAD

**Issue by AngryRoleplayer** [fikal/PoeTradeItemCopy#7]
the script is on but tampermonkey says there's no scripts running
![snag-0009](https://user-images.githubusercontent.com/22470478/30532925-7cc04ab6-9c5f-11e7-8639-e8d53e2c257d.jpg)

**Comment by StarScream159** [comment]
The script won't be "running" until triggered. And it is only triggered on the poe.trade domain.

**Comment by StrikerToastYT** [comment]
I have the same issue
