### ISSUE TITLE
Abyss jewels into PathOfBuilding get the message The items is invalid

### ISSUE THREAD

**Issue by decayedCell** [fikal/PoeTradeItemCopy#8]
Is it something on this end or something PoB needs to fix?

**Comment by earnil** [comment]
From what I tested, name and type of item need to be on two lines. For example:

Rarity: Rare
Morbid Spell Searching Eye Jewel
Item Level: 77
LevelReq: 60
Quality: 0
Implicits: 0
Adds 18 to 40 Fire Damage to Attacks
Adds 1 to 29 Lightning Damage to Attacks
Adds 2 to 27 Lightning Damage to Wand Attacks
Adds 22 to 33 Fire Damage to Wand Attacks

Should be:

Rarity: Rare
Morbid Spell 
Searching Eye Jewel
Item Level: 77
LevelReq: 60
Quality: 0
Implicits: 0
Adds 18 to 40 Fire Damage to Attacks
Adds 1 to 29 Lightning Damage to Attacks
Adds 2 to 27 Lightning Damage to Wand Attacks
Adds 22 to 33 Fire Damage to Wand Attacks

**Comment by earnil** [comment]
items_types tab is just missing new jewels types: "Ghastly Eye Jewel", "Hypnotic Eye Jewel", "Murderous Eye Jewel", "Searching Eye Jewel"
